### ISSUE TITLE
Stuck in infinite input loop

### ISSUE THREAD

**Issue by Wouter-Lemoine** [synio-wesley/qpasm#3]
When creating an infinite loop with inputs (though not on purpose), the code execution cannot be stopped because the input box overwrites the clicks on the stop button.

**Comment by synio-wesley** [comment]
Hi, thanks for the bug report. I am not actively maintaining this software anymore. If you would like to fix this issue, feel free to send a PR. I will then integrate your bugfix. Thanks.

**Comment by synio-wesley** [comment]
@GyroW Thanks for the bug report and PR.

I have made a few changes to the code to fix the problem.
- The 'Stop' button can now be used even when input is being requested. (Or alternatively, as in your original solution, you can click the 'Stop program' button in the input dialog).
- Qt 5 compatibility has also been added.

I have released a new version (1.3) for Windows only right now. If someone would like to release a version for Linux and/or Mac OS X, then please get in touch.

Thanks again. I have added a 'Thanks to' note linking to your GitHub for your help, inside of the Info dialog.
